site_name: Windows Forensics
theme: material
site_author: James Illing
copyright: James Illing
plugins:
  - search
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false
not_in_nav: |
  index.md